name: soap
version: 0.0.1
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
author: Eduardo Carísio <eduardo_carisio@hotmail.com>
homepage: https://example-pet-store.com/newtify
documentation: https://example-pet-store.com/newtify/docs
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  xml: ^3.5.0
  json_serializable: ^3.2.3
  json_annotation: ^3.0.0
  http: ^0.12.0+2
dev_dependencies:
  build_runner: ^1.0.0
  test: ^1.9.2
