name: soap
version: 0.0.1
description: >-
  Convert Map<String, dynamic> to SOAP Envelope XML
author: Eduardo Carísio <eduardo_carisio@hotmail.com>
homepage: https://github.com/eduardocp/soap_parser
documentation: https://github.com/eduardocp/soap_parser
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  xml: any
  intl: any
  analyzer: ">=0.37.1 <0.39.0"
  build: any
  build_config: ^0.4.1+1
  source_gen: ^0.9.0
  meta: ^1.1.0
  path: ^1.3.2
dev_dependencies:
  build_runner: ^1.0.0
  test: ^1.9.2
