# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      soap_serializable:
        generate_for:
          - example/*
          - test/default_value/*
          - test/generic_files/*
          - test/integration/*
          - test/kitchen_sink/*
          - test/literal/*

      build_web_compilers|entrypoint:
        generate_for:
          - test/default_value/**.browser_test.dart
          - test/generic_files/*.browser_test.dart
          - test/integration/*.browser_test.dart
          - test/kitchen_sink/**.browser_test.dart

      soap_serializable|_internal:
        generate_for:
          - test/default_value/default_value.dart
          - test/kitchen_sink/kitchen_sink.dart
          - test/integration/soap_test_example.dart
          - test/generic_files/generic_class.dart
          - test/integration/soap_test_example.dart
          - test/integration/soap_test_example.non_nullable.dart

builders:
  _internal:
    import: "tool/test_builder.dart"
    builder_factories: ["internal"]
    build_extensions:
      .dart:
        - .factories.dart
        - .g_any_map.dart
        - .g_any_map__checked.dart
        - .g_any_map__checked__non_nullable.dart
        - .g_any_map__non_nullable.dart
        - .g_exclude_null.dart
        - .g_exclude_null__non_nullable.dart
        - .g_explicit_to_soap.dart
        - .g_non_nullable.dart
    build_to: source
    runs_before: ["soap_serializable"]

  _doc_builder:
    import: "tool/doc_builder.dart"
    builder_factories: ["docBuilder"]
    build_extensions: { "lib/soap_serializable.dart": ["doc/doc.md"] }
    build_to: source
    auto_apply: root_package
    runs_before: ["soap_serializable"]
    required_inputs: ["doc/soap_annotation_version.txt"]

  soap_serializable:
    import: "package:soap_serializable/builder.dart"
    builder_factories: ["soapSerializable"]
    build_extensions: { ".dart": ["soap_serializable.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
